name: tager_paraffin
description: Trading App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^9.0.0
  build_runner: ^2.4.14
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.4.0
  flutter_localization: ^0.3.3
  flutter_polyline_points: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^8.0.3
  go_router: ^16.1.0
  google_maps_flutter: ^2.10.0
  google_maps_webapi: ^0.0.24
  google_sign_in: ^7.1.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_serializable: ^6.9.3
  loading_animation_widget: ^1.3.0
  location: ^8.0.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sign_in_with_apple: ^7.0.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Robote
      fonts:
        - asset: assets/fonts/Roboto/Roboto-light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23
