name: tager_paraffin
description: Trading App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^9.0.0
  build_runner: ^2.4.14
  cloud_firestore: ^5.6.3
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  firebase_messaging: 15.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  json_serializable: ^6.9.3
  loading_animation_widget: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Robote
      fonts:
        - asset: assets/fonts/Roboto/Roboto-light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23
