// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtpSSwdS_Gwp92l17RiiAYxtE5wmUHvw4',
    appId: '1:770964686305:android:e54d2924e0b7138ae43ea0',
    messagingSenderId: '770964686305',
    projectId: 'tajer-paraffin',
    storageBucket: 'tajer-paraffin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz46pYFXpWmE4rn8b5qT1yxtXltFiV9yA',
    appId: '1:770964686305:ios:3e0c79b33b698683e43ea0',
    messagingSenderId: '770964686305',
    projectId: 'tajer-paraffin',
    storageBucket: 'tajer-paraffin.firebasestorage.app',
    androidClientId:
        '770964686305-aipp2e1s3jls4u6foosu8g4kg8muuo3j.apps.googleusercontent.com',
    iosClientId:
        '770964686305-bbpsflfti0h0fp4e11lj42rf0ir2iiop.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagerParaffin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYWxaxLonrzRESSKqMy5spKCi8zIS7FmU',
    appId: '1:770964686305:web:ceafe636b2cd777be43ea0',
    messagingSenderId: '770964686305',
    projectId: 'tajer-paraffin',
    authDomain: 'tajer-paraffin.firebaseapp.com',
    storageBucket: 'tajer-paraffin.firebasestorage.app',
    measurementId: 'G-XLJ2T7518S',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYWxaxLonrzRESSKqMy5spKCi8zIS7FmU',
    appId: '1:770964686305:web:9f207949c290b011e43ea0',
    messagingSenderId: '770964686305',
    projectId: 'tajer-paraffin',
    authDomain: 'tajer-paraffin.firebaseapp.com',
    storageBucket: 'tajer-paraffin.firebasestorage.app',
    measurementId: 'G-WJPR2GFPNG',
  );
}
