// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Btjv7iwQUvXkktlSq37ZlFdKfPCWr9w',
    appId: '1:57316890248:android:763dd0be67ed83827d313d',
    messagingSenderId: '57316890248',
    projectId: 'tager-paraffin',
    storageBucket: 'tager-paraffin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1vR_MyCKtADKRc4usIYk9z382lQ95qfM',
    appId: '1:57316890248:ios:66e21533e0f3706b7d313d',
    messagingSenderId: '57316890248',
    projectId: 'tager-paraffin',
    storageBucket: 'tager-paraffin.appspot.com',
    androidClientId: '57316890248-886l3cismagk54l544kdapvn2kqo0atu.apps.googleusercontent.com',
    iosClientId: '57316890248-5vm9l4r18i3cj0o88tnmvi5mc9a26pbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagerParaffin',
  );
}
